DicDatosFormMon={
    "CND":["CENTRO","MEC","OCCIDENTE","ORIENTE"],
    "CUENTA":"Claro CND BOGOTA",
    "CIUDAD":["BOGOTA","CALI","BUCARAMANGA"],
    "AREAMON":["CALIDAD","CLARO","MEC","SUPERVISOR","FORMACION"],    
    "TIPOAUD":["MUESTRA","REMOTO","LADO A LADO","PANTALLA"],
    "PORCESO":["DESPACHO","BACKLOG","HHPP"],
    "CUMPLIMIENTO":['Cumple','No cumple'],    
    "COMODIN2":[1,2,3,4,5,"N/A"],
    #"Tiempos":ArrayRangos
}


DicDatosOts={"TIPOORDEN":
                ["Arreglo","Blindaje","Brownfield","Instalacion","postventa","Traslado"],
                "RAZONES":["B - DIRECCION Y/O DATOS ERRADOS",
                    "C - NO CONTACTO CON EL CLIENTE",
                    "E - SUSCRIPTOR NO DESEA/NO REQUIERE TRABAJOS",
                    "F - FALTA DE MATERIALES/EQUIPOS CLARO",
                    "H - REQUIERE AMPLIACIÓN DE PUERTOS",
                    "I - INCUMPLIMIENTO ALIADO",
                    "K - CLIENTE SOLICITA REPROGRAMAR",
                    "L - LLUVIA - FACTORES CLIMÁTICOS",
                    "M - MAL AGENDADO/MAL PROGRAMADO",
                    "N - ESCALAMIENTO NOC",
                    "O - CLIENTE NO TIENE DINERO",
                    "P - PERMISOS DE ADMINISTRACION",
                    "Q - PROBLEMAS EN SISTEMAS-APLICATIVOS CLARO",
                    "R - REPLANTEAMIENTO VT",
                    "S - NO INGRESO/CLIENTE CONFIRMA SERVICIO OK",
                    "V - UNIDAD POSIBLE FRAUDE",
                    "W - DUCTOS/INFRESTRUCTURA PREDIO NO APTA",
                    "X - PROBLEMA ORDEN PUBLICO/ZONA ROJA",
                    "Y - INSTALACIÓN REQUIERE ANDAMIO-ARNES",
                    "Z - FUERA ZONA/ SIN COBERTURA RED",
                    "4 - VENTA DEVUELTA AL ASESOR",
                    "5 - PROBLEMA TARIFA/SERVICIOS DIGITADO",
                    "6 - EQUIPOS CLIENTE NO APTOS/NO DISPONIBLES",
                    "7 - CLIENTE AUN NO DESEA EL TRABAJO",
                    "? - SUSCRIPTOR NO ESTA EN CONDICIÓN DE ATENDER",
                    "(+) - CAMARA/SOLDADA O INUNDADA",
                    "(=) - REQUIERE MOVIL ELITE",
                    "/ - FUERA DE COBERTURA WTTH",
                    "@ - ESCALAMIENTO NOC @",
                    "# - ESCALAMIENTO NOC TV",
                    "$ - ESCALAMIENTO NOC TELEFONIA",
                    "'%' - ESCALAMIENTO NOC RED BI",
                    "& - ESCALAMIENTO NOC PYMES",
                    "GESTION BACKLOG",
                    "MINTIC",
                    "CONFIRMACION",
                    "ENRUTAMIENTO",
                    "VISITA OK FO"]
                }

DicDatosOtsHhpp={"TIPOORDEN":["Creación Hhpp Bidireccional","Cambio De Dirección Hhpp","Creación Hhpp Mer",
                "Modificación Cm / Mer","Cambio Estrato Suscriptor","Creación Cm","Creación Hhpp En Cm","Modificar Eliminar Cm / Mgl",
                "Cambio Estrato Cm","Reactivación Hhpp","Fichas"
                ],"RAZONES":[
                        "BARRIO DUPLICADO EN LA SOLICITUD",
                        "CAMBIO DE DIRECCION NO REALIZADO",
                        "CAMBIO DE DIRECCION REALIZADO",
                        "CARACTER NO VALIDO EN UNIDAD A MODIFICAR",
                        "CONFIRMAR DISTRIBUCION DE HHPP EXISTENTE",
                        "DATOS DE DIRECCION INCOMPLETOS",
                        "DIRECCION ASOCIADA A CUENTA MATRIZ",
                        "FUERA DE ZONA",
                        "GESTION DE HHPP DE FORMA MANUAL",
                        "HHPP ACTUALIZADO",
                        "HHPP CREADO",
                        "HHPP EN USO POR OTRO USUARIO",
                        "HHPP YA EXISTE EN RR",
                        "NO SE CREAN HHPP EN NODO APAGADO",
                        "REACTIVACION HHPP NO REALIZADO",
                        "REACTIVACION HHPP REALIZADO",
                        "SOLICITAR POR EL LINK MGL",
                        "SOLICITUD MAL REALIZADA",
                        "VERIFICACION AGENDANDA",
                        "CUENTA MATRIZ CREADA",
                        "CUENTA MATRIZ CON O SIN VT NO SE CREA EL HHPP",
                        "CAMBIO DE ESTRATO REALIZADO",
                        "CUENTA MATRIZ ACTUALIZADA",
                        "SOLICITUD REPETIDA",
                        "CUENTA MATRIZ YA EXISTE EN RR",
                        "CUENTA MATRIZ CREADA",
                        "NO SE PUBLICO DOCUMENTO DE SOPORTE",
                        "GESTION REALIZADA",
                        "BARRIO DUPLICADO EN LA SOLICITUD",
                        "SOPORTE NO VALIDO",
                        "SOPORTE NO SE DEJA VISUALIZAR",
                        "SOPORTE CON ENMENDADURA",
                        "HHPP CON OT ABIERTA",
                        "CAMBIO DE ESTRATO YA EXISTE EN RR",
                        "DIRECCION INCOMPLETA",
                        "HHPP CREADOS",
                        "NO HAY PUBLICACION DE VT",
                        "HHPP HABILITADO",
                        "CUENTA MATRIZ ELIMINADA",
                        "VERIFICACION AGENDADA",
                        "CAMBIO DE NODO REALIZADO",
                        "RECHAZAR ELIMINACION CM",
                        ]}


dicMes={'Enero':1, 'Febrero':2, 'Marzo':3, 'Abril':4, 'Mayo':5, 'Junio':6,'Julio':7, 'Agosto':8, 'Septiembre':9, 'Octubre':10, 'Noviembre':11, 'Diciembre':12}

DicGen={"Backoffice":[1,2,3],
            "Labor":["Crear","Completar","Marcar Confirmacion","Marcar Demora","Marcar Seguimiento","Marcacion Soporte","Marcacion TAM","Marcacion Multiple","Repara y Actualiza","Actualizar","Marcacion MiN & PY"],
            "Ciudad":["Bogota","Cali"]}


DicOpciones={
    "Razones":[
        'AMPLIACION DE TAP HFC',
        'AMPLIACION DE TAP FTTH',
        'CAMARA/SOLDADA O INUNDADA',
        'CLIENTE AUN NO DESEA EL TRABAJO',
        'CLIENTE NO TIENE DINERO',
        'CLIENTE SOLICITA REPROGRAMAR',
        'DIRECCION Y/O DATOS ERRADOS',
        'DUCTOS/INFRESTRUCTURA PREDIO NO APTA',
        'EQUIPOS CLIENTE NO APTOS/NO DISPONIBLES',
        'FALTA DE MATERIALES/EQUIPOS',
        'FUERA DE COBERTURA WTTH',
        'FUERA DE ZONA',
        'INCUMPLIMIENTO ALIADO',
        'INSTALACIÓN REQUIERE ANDAMIO ARNES',
        'LLUVIA - FACTORES CLIMÁTICOS',
        'MAL AGENDADO/MAL PROGRAMADO',
        'NO CONTACTO CON CLIENTE',
        'NO INGRESO/CLIENTE CONFIRMA SERVICIO OK',
        'PERMISOS DE ADMINISTRACION',
        'PROBLEMA ORDEN PUBLICO/ZONA ROJA',
        'PROBLEMAS EN LA RED EXTERNA',
        'PROBLEMAS EN SISTEMAS APLICATIVOS CLARO',
        'REPLANTEAMIENTO',
        'REQUIERE MOVIL ELITE',
        'SUSCRIPTOR NO DESEA/NO REQUIERE TRABAJOS',
        'SUSCRIPTOR NO ESTA EN CONDICIÓN DE ATENDER',
        'UNIDAD POSIBLE FRAUDE',
        'VENTA DEVUELTA AL ASESOR']
}

dicCiudad={"BOGOTA":1,"BUCARAMANGA":1,"CALI":2}