version: "3"

services: 
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome
    ports:
      - 4446:4444
      - 0.0.0.0:9222:9222
    restart: always 

  app:
    build: 
      context: .
    volumes:
      - ./app:/app
    environment:
      - BOT_NAME=${BOT_NAME}
